Feat/support ndk crash reporting
Instabug/Instabug-React-Native pull request #1043
Opened 2023-10-22 16:33 UTC by abdelhamid-f-nasser

## Description of the change

Support c++ code ndk crash reporting

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

Jira ID: [IBGCRASH-20274](https://instabug.atlassian.net/browse/IBGCRASH-20274)

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2023-10-22 16:36 UTC, abdelhamid-f-nasser commented
@a7medev Should I add tests for this, as I have found the tests to be commented out in `RNInstabugCrashReportingModuleTest`.

2023-10-23 08:02 UTC, InstabugCI commented
<!--
  0 failure: 
  1 warning:  You have not incl...
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  You have not included a CHANGELOG entry! 
You can find it at [CHANGELOG.md](https://github.com/Instabug/Instabug-React-Native/blob/master/CHANGELOG.md).
  </td>
    </tr>
  </tbody>
</table>


### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| JavaScript | 95.9% | ✅ |
| Android | 49.6% | ✅ |
| iOS | 40.5% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b1426387ab12f31ec0fc9db331fc3c8ec9d74267
</p>

2023-10-25 13:09 UTC, a7medev requested changes

2023-10-25 13:09 UTC, a7medev commented on examples/default/src/screens/CrashReportingScreen.tsx
> +            Alert.alert('NDK crashes is only available on Android.');
Just a small typo 🔍
```suggestion
            Alert.alert('NDK crashes are only available on Android.');
```

2023-11-01 08:45 UTC, abdelhamid-f-nasser commented
We'll have to re-create this PR, into a new consolidated repo which exposes the NDK crash reporting as a stand-alone dependency.

2023-11-01 08:45 UTC, closed without merging