feat/add-mapping-to-enable-ndk-crash
Instabug/Instabug-React-Native pull request #1132
Opened 2024-02-11 18:19 UTC by ahmedAlaaInstabug

## Description of the change

1) Map setNDKCrashesEnabled in Javascript side

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

JIRA-TICKET=[MOB-13774]https://instabug.atlassian.net/browse/MOB-13774

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2024-02-13 00:46 UTC, mnoseir commented
<!--
  0 failure: 
  1 warning:  You have not incl...
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  You have not included a CHANGELOG entry! 
You can find it at [CHANGELOG.md](https://github.com/Instabug/Instabug-React-Native/blob/master/CHANGELOG.md).
  </td>
    </tr>
  </tbody>
</table>


### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| JavaScript | 96.3% | ✅ |
| Android | 47.5% | ✅ |
| iOS | 41.3% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f73bd74598d41905a7084e43866d57fdda63b92d
</p>

2024-02-13 08:41 UTC, abdelhamid-f-nasser requested changes
Great effort @ahmedAlaaInstabug !! Please check my suggestions. 🙏

2024-02-13 11:50 UTC, ahmedAlaaInstabug commented on android/src/test/java/com/instabug/reactlibrary/RNInstabugCrashReportingModuleTest.java
> +    public void givenTrue$SetNDKCrashesEnabledShouldCallNativeApiWithDisabled() {
@abdelhamid-f-nasser fixed

2024-02-13 12:46 UTC, a7medev requested changes
LGTM 👏🏼, please check the comment I added. Let's also add a changelog entry as Abdelhamid suggested 🙏🏼.

2024-02-15 11:22 UTC, ahmedAlaaInstabug commented on src/modules/CrashReporting.ts
> +  InstabugUtils.sendCrashReport(error, NativeCrashReporting.sendHandledJSCrash);
fixed @a7medev

2024-02-18 12:45 UTC, abdelhamid-f-nasser commented on CHANGELOG.md
> +- Add support for enable NDK crashes on Android ([#1132](https://github.com/Instabug/Instabug-React-Native/pull/1132))
How about we change it to either one of the below ?
```suggestion
- Add support for enabling NDK crash capturing on Android ([#1132](https://github.com/Instabug/Instabug-React-Native/pull/1132))
```

```suggestion
- Support enabling NDK crash capturing on Android ([#1132](https://github.com/Instabug/Instabug-React-Native/pull/1132))
```

2024-02-18 17:24 UTC, abdelhamid-f-nasser commented on CHANGELOG.md
> +- Support enabling NDK crash capturing on Android ([#1132](https://github.com/Instabug/Instabug-React-Native/pull/1132))
Lets add a the missing `.` 🙈 .

```suggestion
- Support enabling NDK crash capturing on Android ([#1132](https://github.com/Instabug/Instabug-React-Native/pull/1132)).
```

2024-02-19 12:27 UTC, abdelhamid-f-nasser approved these changes

2024-02-19 12:28 UTC, merged