feat: Mapping-Session-Replay-links-api
Instabug/Instabug-React-Native pull request #1142
Opened 2024-02-20 16:21 UTC by ahmedAlaaInstabug

## Description of the change

1. Map OnSessionReplayLinkReady API that Retrieves the current session's replay link.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

Jira-id=[MOB-14010](https://instabug.atlassian.net/browse/MOB-14010)

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2024-02-20 16:33 UTC, mnoseir commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| JavaScript | 96.3% | ✅ |
| Android | 47.5% | ✅ |
| iOS | 41.5% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c535cead22e2f4d15496d105c63b2939b3493992
</p>

2024-02-25 14:13 UTC, a7medev requested changes
Great job, Alaa 👏🏼! Can you please check the comments I've added? 🙏🏼

2024-02-25 14:13 UTC, a7medev commented on test/modules/SessionReplay.spec.ts
> +    expect(NativeSessionReplay.getSessionReplayLink).toBeCalledTimes(1);
I think we also need to assert that it returns whatever value `NativeSessionReplay.getSessionReplayLink` returns which means we also need to mock the returned value of `NativeSessionReplay.getSessionReplayLink` then verify that `SessionReplay.getSessionReplayLink` returns the same value.

What do you think?

2024-02-25 17:37 UTC, abdelhamid-f-nasser approved these changes
@ahmedAlaaInstabug Great effort and yet another great feature 👏 💪 !!!

2024-02-25 17:39 UTC, merged