fix(ios): network log empty response body
Instabug/Instabug-React-Native pull request #1273
Opened 2024-08-16 11:02 UTC by ahmedAlaaInstabug

## Description of the change

fix(ios): network log empty response body

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

JIRA ID: INSD-12058

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2024-08-16 11:39 UTC, InstabugCI commented
<!--
  0 failure: 
  1 warning:  You have not incl...
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  You have not included a CHANGELOG entry! 
You can find it at [CHANGELOG.md](https://github.com/Instabug/Instabug-React-Native/blob/master/CHANGELOG.md).
  </td>
    </tr>
  </tbody>
</table>


### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| JavaScript | 99.0% | ✅ |
| Android | 50.2% | ✅ |
| iOS | 47.9% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d62d374a425b7150150c94d0019d51d87f8e2c92
</p>

2024-08-16 12:05 UTC, InstabugCI commented
Your snapshot has been generated! :rocket:

### Installation

You can install the snapshot through NPM:

```sh
npm install https://github.com/Instabug/Instabug-React-Native\#snapshot/fix/network-ios-log-empty-response-body
```

or Yarn:

```sh
yarn add https://github.com/Instabug/Instabug-React-Native\#snapshot/fix/network-ios-log-empty-response-body
```

2024-09-10 12:26 UTC, a7medev requested changes
Let's please add a changelog item for this PR 🙏🏼

2024-09-12 09:09 UTC, a7medev requested changes

2024-09-12 09:09 UTC, a7medev commented on CHANGELOG.md
> +- Fix APM network logging on iOS when the response body is missing or empty. ([#1253](https://github.com/Instabug/Instabug-React-Native/pull/1253)).
```suggestion
- Add support for Expo Router navigation tracking ([#1270](https://github.com/Instabug/Instabug-React-Native/pull/1270)).

### Fixed

- Fix APM network logging on iOS when the response body is missing or empty. ([#1273](https://github.com/Instabug/Instabug-React-Native/pull/1273)).
```

2024-09-15 10:02 UTC, a7medev submitted a review, later dismissed

2024-09-15 13:52 UTC, AyaMahmoud148 submitted a review, later dismissed

2024-09-15 15:55 UTC, AndrewAminInstabug approved these changes

2024-09-15 17:48 UTC, a7medev approved these changes

2024-09-16 08:02 UTC, merged