fix: omitted non error objects when logging errors
Instabug/Instabug-React-Native pull request #1279
Opened 2024-08-23 11:43 UTC by ahmedAlaaInstabug

## Description of the change

1.Fix Omitted non-error objects when logging errors to ensure only error objects are supported

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

JIRA ID: CRASHES-22610

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2024-08-23 11:56 UTC, InstabugCI commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| JavaScript | 98.7% | ✅ |
| Android | 50.2% | ✅ |
| iOS | 47.9% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 67ed3dc0fc9f5a64c6faf125a7d3ac1703fb30ac
</p>

2024-08-28 07:49 UTC, a7medev requested changes

2024-08-28 07:49 UTC, a7medev commented on src/modules/CrashReporting.ts
> +    console.log(
I think this should be a warning, what do you think?
```suggestion
    console.warn(
```

2024-08-28 07:49 UTC, a7medev commented on CHANGELOG.md
> +- Fix Omitted non-error objects when logging errors to ensure only error objects are supported.([#1279](https://github.com/Instabug/Instabug-React-Native/pull/1279)).
```suggestion
- Drop non-error objects passed to `CrashReporting.reportError` as they don't have a stack trace ([#1279](https://github.com/Instabug/Instabug-React-Native/pull/1279)).
```

2024-08-28 07:51 UTC, a7medev commented
@ahmedAlaaInstabug Do you think we should omit non-error objects captured automatically as unhandled crashes?

2024-09-12 09:06 UTC, a7medev submitted a review, later dismissed

2024-09-15 13:54 UTC, AyaMahmoud148 submitted a review, later dismissed

2024-09-15 15:59 UTC, AndrewAminInstabug approved these changes

2024-09-15 17:51 UTC, a7medev approved these changes

2024-09-16 09:48 UTC, AyaMahmoud148 approved these changes

2024-09-16 09:55 UTC, AndrewAminInstabug approved these changes

2024-09-16 09:55 UTC, merged