upgrade: native iOS snapshot to 14.0.0
Instabug/Instabug-React-Native pull request #1334
Opened 2024-12-18 10:57 UTC by AndrewAminInstabug

## Description of the change

[> Description goes here](upgrade: native iOS snapshot to 14.0.0)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Issue links go here

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2025-01-09 01:59 UTC, ahmedAlaaInstabug requested changes
Ci jobs is failed

2025-01-09 10:15 UTC, InstabugCI commented
<!--
  1 failure:  Please provide a ...
  2 warning:  Coverage for Java..., You have not incl...
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please provide a summary of the changes in the pull request description.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Coverage for JavaScript is less than the expected threshold of 90%</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  You have not included a CHANGELOG entry! 
You can find it at [CHANGELOG.md](https://github.com/Instabug/Instabug-React-Native/blob/master/CHANGELOG.md).
  </td>
    </tr>
  </tbody>
</table>


### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| JavaScript | 89.4% | ❌ |
| Android | 49.6% | ✅ |
| iOS | 44.3% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5de5fc43d33d6fc943b3479910a1dd2eac7db89d
</p>

2025-01-13 15:29 UTC, ahmedAlaaInstabug approved these changes

2025-01-14 09:35 UTC, kholood-ea approved these changes

2025-01-19 13:53 UTC, merged