[MOB-8995] Drop Manual Linking Support
Instabug/Instabug-React-Native pull request #748
Opened 2022-08-25 13:53 UTC by DavidMina96

## Description of the change

- Remove (un)linking-related files and scripts for both platforms
- Remove `hooks` property from `react-native.config.js` file
- Remove the no-longer-needed maven repo from the Sample app
- Specify a minimum `react-native` version in `peerDependencies` (0.60.0)

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Related issues
> Issue links go here
## Checklists
### Development
- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
### Code review 
- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] Issue from task tracker has a link to this pull request

2022-08-25 13:56 UTC, TheBuggedYRN commented on package.json
>        "packageInstance": "new RNInstabugReactnativePackage()"
Is this still needed as well?

2022-08-26 11:31 UTC, TheBuggedYRN requested changes
We need a Changelog entry as well.

2022-08-26 14:25 UTC, a7med-mahmoud commented on package.json
>        "packageInstance": "new RNInstabugReactnativePackage()"
I don't think so, we can remove it

2022-08-28 12:53 UTC, a7med-mahmoud approved these changes
Sounds good to me. I'm just curious, do we need the README file to be formatted in this PR?

2022-08-28 12:59 UTC, DavidMina96 commented
@a7med-mahmoud Not necessarily, but since I had to update already within the PR's scope, I applied the formatting changes as well.

2022-08-30 09:49 UTC, TheBuggedYRN submitted a review, later dismissed

2022-08-30 09:59 UTC, AliAbdelfattah commented on README.md
> +        ```
When you display the rich diff, ` ```javascript ` is shown as part of the snippet code.

2022-08-30 09:59 UTC, AliAbdelfattah commented on CHANGELOG.md
> +* Bumps the minimum supported React Native version to 0.60.0
Please add an item for dropping the manual linking support.

2022-08-30 12:33 UTC, TheBuggedYRN approved these changes

2022-08-30 12:59 UTC, AliAbdelfattah approved these changes

2022-08-30 13:00 UTC, a7med-mahmoud approved these changes

2022-08-30 13:13 UTC, merged