Add Interfaces for Native Modules
Instabug/Instabug-React-Native pull request #918
Opened 2023-02-16 14:24 UTC by TheBuggedYRN

- Create `native` directory
- Add APM types
- Add BugReporting types
- Add CrashReporting types
- Add FeatureRequests types
- Add Instabug types
- Add Constants types
- Add Replies types
- Add Surveys types
- Fix failing CrashReporting tests
- Fix failing APM tests

## Description of the change

> Description goes here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Issue links go here

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2023-02-23 13:02 UTC, a7medev requested changes
This is a huge step towards better DX and more type-safety and is definitely something that will make the New Architecture migration a breeze 👏❤️

2023-02-26 10:10 UTC, TheBuggedYRN commented on src/native/BugReportingNativeModule.ts
> +  // Essential APIs//
It might sound like a small suggestion, but I appreciate such ones!

2023-02-26 10:10 UTC, TheBuggedYRN commented on src/native/FeatureRequestsNativeModule.ts
> +  ): void;
Nice catch!

2023-02-26 10:12 UTC, TheBuggedYRN commented on src/native/InstabugNativeModule.ts
> +  getReport(): void;
I ended up removing it. The PR was based on an old `dev` branch that had this method back then, and it was not removed after rebasing.

2023-02-26 10:34 UTC, TheBuggedYRN commented on test/modules/APM.spec.ts
> +    NativeAPM.startExecutionTrace = jest
That's a nice util. I believe we need to enhance our mock types everywhere along the code but I cannot see any other similar usage **related to native modules** for now. So let's keep that change scoped to the PR, and apply everywhere else in other PR.

2023-02-26 11:09 UTC, a7medev approved these changes

2023-02-26 14:05 UTC, merged