[MOB-12511] Replace `Enabled` Method with `Required` Prop in JaCoCo Gradle Plugin
Instabug/Instabug-React-Native pull request #995
Opened 2023-07-03 08:59 UTC by asamiz

## Description of the change

Replace the `enabled` method with `required` property in JaCoCo `gradle` plugin as it breaks the gradle scripts running on version `0.72`.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues
#994 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] Issue from task tracker has a link to this pull request

2023-07-03 09:24 UTC, InstabugCI commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



### Coverage Report
| Label | Coverage | Status |
| ----- | -------- | ------ |
| JavaScript | 96.5% | ✅ |
| Android | 47.8% | ✅ |
| iOS | 39.0% | ✅ |
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3dc77d61b651a4a2987906561e9119ca1df1b85b
</p>

2023-07-03 10:27 UTC, a7medev commented on android/jacoco.gradle
> +    xml.required=true
```suggestion
    html.required = true
    xml.required = true
```

2023-07-03 11:46 UTC, asamiz commented on android/jacoco.gradle
> +    xml.required=true
Done.

2023-07-03 12:13 UTC, a7medev approved these changes

2023-07-03 12:15 UTC, a7medev requested changes
@asamiz One last change, please add a changelog item for this change 🙏🏼

2023-07-04 08:16 UTC, a7medev approved these changes

2023-07-05 09:20 UTC, merged